name: WPF Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build the solution
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    # Execute unit tests
    - name: Run tests
      run: dotnet test --configuration ${{ matrix.configuration }}
