jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Change directory to solution
      run: cd D:\FPT_Learning\PRN221\WPF-RentalMotorBike

    - name: Restore dependencies
      run: dotnet restore WPF-RentalMotorBike.sln

    - name: Build the solution
      run: dotnet build WPF-RentalMotorBike.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test WPF-RentalMotorBike.sln --no-build --verbosity normal
