name: .NET Core Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./RentalMotorbike.sln

    - name: Build the solution
      run: dotnet build ./RentalMotorbike.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test ./RentalMotorbike.sln --no-build --verbosity normal

    - name: Publish the application
      run: dotnet publish ./RentalMotorbike.sln --configuration Release --output ./output

    - name: Archive the output
      uses: actions/upload-artifact@v3
      with:
        name: RentalMotorbike
        path: ./output
