name: .NET Core Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: List files in src
      run: dir ./src # Liệt kê các tệp trong thư mục src

    - name: Restore dependencies
      run: dotnet restore ./src/RentalMotorbike.sln # Đường dẫn tới tệp giải pháp

    - name: Build the solution
      run: dotnet build ./src/RentalMotorbike.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test ./src/RentalMotorbike.sln --no-build --verbosity normal

    - name: List files
      run: dir ./src # Kiểm tra các tệp trong thư mục src
